resolver: lts-15.0
packages:
- .
- VulkanMemoryAllocator
extra-deps:
- github: haskell-game/sdl2
  commit: 45679ab73fe4113eeae3b17ecaa2bec3b00bfd81
nix:
  enable: false
  packages: [vulkan-loader vulkan-headers glslang pkg-config SDL2]
