name: vulkan-examples
version: 0.1.0.0
synopsis: Haskell examples for the Vulkan graphics API.
category: Graphics
maintainer: Joe Hermaszewski <live.long.and.prosper@monoid.al>
github: expipiplus1/vulkan
extra-source-files:
  - readme.md
license: BSD-3-Clause

executables:
  info:
    main: Main.hs
    source-dirs: info
    dependencies:
      - base < 4.15
      - vulkan
      - pretty-simple
      - bytestring

  sdl-triangle:
    main: Main.hs
    source-dirs: sdl-triangle
    dependencies:
      - base < 4.15
      - bytestring
      - extra
      - managed
      - pretty-show
      - say
      - sdl2 >= 2.5.2.0
      - text
      - transformers
      - vulkan-utils
      - vector
      - vulkan

  offscreen:
    main: Main.hs
    source-dirs: offscreen
    dependencies:
      - JuicyPixels
      - VulkanMemoryAllocator
      - autoapply >= 0.4
      - base < 4.15
      - bytestring
      - extra
      - resourcet
      - safe-exceptions
      - say
      - text
      - transformers
      - vector
      - vulkan
      - vulkan-utils
    when:
      - condition: flag(renderdoc)
        cpp-options: -DRENDERDOC
        dependencies:
          - containers
          - inline-c
        extra-libraries: dl

  compute:
    main: Main.hs
    source-dirs: compute
    dependencies:
      - JuicyPixels
      - VulkanMemoryAllocator
      - autoapply >= 0.4
      - base < 4.15
      - bytestring
      - extra
      - resourcet
      - safe-exceptions
      - say
      - text
      - transformers
      - vector
      - vulkan
      - vulkan-utils

  resize:
    main: Main.hs
    source-dirs: resize
    dependencies:
      - VulkanMemoryAllocator
      - autoapply >= 0.4
      - base < 4.15
      - bytestring
      - extra
      - resourcet >= 1.2.4
      - safe-exceptions
      - say
      - sdl2 >= 2.5.2.0
      - text
      - transformers
      - unliftio
      - vector
      - vulkan
      - vulkan-utils

flags:
  renderdoc:
    description:
      Use the renderdoc API to mark the beginning and end of the 'offscreen'
      example so that it can be captured.
    default: no
    manual: yes

default-extensions:
  - AllowAmbiguousTypes
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DerivingStrategies
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - LambdaCase
  - MagicHash
  - NoMonomorphismRestriction
  - NumDecimals
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternSynonyms
  - PolyKinds
  - QuantifiedConstraints
  - RankNTypes
  - RecordWildCards
  - RoleAnnotations
  - ScopedTypeVariables
  - StandaloneDeriving
  - Strict
  - TupleSections
  - TypeApplications
  - TypeFamilyDependencies
  - TypeOperators
  - TypeSynonymInstances
  - UndecidableInstances
  - ViewPatterns

ghc-options:
  - -Wall
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
