maintainer: generator.i.ardly.know.er@monoid.al
ghc-options:
- -Wall
- -fno-warn-unticked-promoted-constructors
- -fno-warn-name-shadowing
- -O2
- -flate-specialise
- -fspecialise-aggressively
default-extensions:
- BangPatterns
- BinaryLiterals
- BlockArguments
- ConstraintKinds
- DataKinds
- DeriveGeneric
- DerivingVia
- DisambiguateRecordFields
- DuplicateRecordFields
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MonadComprehensions
- MultiParamTypeClasses
- MultiWayIf
- NoImplicitPrelude
- OverloadedStrings
- ParallelListComp
- PartialTypeSignatures
- PatternSynonyms
- PolyKinds
- RankNTypes
- RecordWildCards
- RecursiveDo
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskellQuotes
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators
- ViewPatterns
name: generate-new
synopsis: A program to generate the vulkan package from the vulkan docs.
author: Joe Hermaszewski

library:
  source-dirs: src

executables:
  vk:
    main: Main.hs
    source-dirs: vk
    dependencies:
      - generate-new
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
  vma:
    main: Main.hs
    source-dirs: vma
    dependencies:
      - generate-new
      - language-c
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

dependencies:
  - algebraic-graphs
  - ascii-progress
  - async-pool
  - base
  - bytestring
  - casing
  - containers
  - data-default
  - deepseq
  - dependent-map
  - dependent-sum >= 0.7
  - directory
  - extra
  - filepath
  - inline-c
  - interpolatedstring-perl6
  - mtl
  - pandoc
  - parsec
  - parsers
  - polysemy
  - polysemy-plugin
  - pretty-show
  - prettyprinter
  - regex-applicative
  - relude
  - safe
  - say
  - some
  - tagsoup
  - template-haskell
  - text
  - th-abstraction
  - th-desugar >= 1.11
  - th-orphans
  - timeit
  - transformers
  - typed-process
  - uniplate
  - unordered-containers
  - vector
  - vector-algorithms
  - word-wrap
  - xeno
