license-file: ../LICENSE
maintainer: generator.i.ardly.know.er@monoid.al
ghc-options:
- -threaded
- -rtsopts
- -with-rtsopts=-N
- -Wall
- -fno-warn-unticked-promoted-constructors
- -fplugin=Polysemy.Plugin
default-extensions:
- BangPatterns
- BinaryLiterals
- ConstraintKinds
- DataKinds
- DeriveGeneric
- DerivingVia
- DisambiguateRecordFields
- DuplicateRecordFields
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTSyntax
- InstanceSigs
- KindSignatures
- LambdaCase
- MonadComprehensions
- MultiParamTypeClasses
- MultiWayIf
- NoImplicitPrelude
- OverloadedStrings
- ParallelListComp
- PartialTypeSignatures
- PatternSynonyms
- RankNTypes
- RecordWildCards
- RecursiveDo
- ScopedTypeVariables
- StandaloneDeriving
- Strict
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators
- ViewPatterns
name: generate-new
synopsis: A program to generate the vulkan package from the vulkan docs.
author: Joe Hermaszewski
executables:
  generate:
    source-dirs: src
    main: Main.hs
    dependencies:
    - th-orphans
    - template-haskell
    - base
    - bytestring
    - inline-c
    - interpolatedstring-perl6
    - polysemy
    - polysemy-plugin
    - pretty-show
    - prettyprinter
    - relude
    - say
    - tagsoup
    - text
    - uniplate
    - unordered-containers
    - vector
    - xeno
description: Please see README.md
