license-file: ../LICENSE
maintainer: generator.i.ardly.know.er@monoid.al
ghc-options:
- -threaded
- -rtsopts
- -with-rtsopts=-N
- -Wall
- -fno-warn-unticked-promoted-constructors
- -fno-warn-name-shadowing
# - -fplugin=Polysemy.Plugin
- -O2
- -flate-specialise
- -fspecialise-aggressively
default-extensions:
- BangPatterns
- BinaryLiterals
- BlockArguments
- ConstraintKinds
- DataKinds
- DeriveGeneric
- DerivingVia
- DisambiguateRecordFields
- DuplicateRecordFields
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MonadComprehensions
- MultiParamTypeClasses
- MultiWayIf
- NoImplicitPrelude
- OverloadedStrings
- ParallelListComp
- PartialTypeSignatures
- PatternSynonyms
- PolyKinds
- RankNTypes
- RecordWildCards
- RecursiveDo
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskellQuotes
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators
- ViewPatterns
name: generate-new
synopsis: A program to generate the vulkan package from the vulkan docs.
author: Joe Hermaszewski
executables:
  generate:
    source-dirs: src
    main: Main.hs
    dependencies:
    - algebraic-graphs
    - base
    - bytestring
    - containers
    - deepseq
    - dependent-sum
    - dependent-map
    - directory
    - extra
    - filepath
    - inline-c
    - interpolatedstring-perl6
    - parsec
    - polysemy
    - polysemy-zoo
    - polysemy-plugin
    - pretty-show
    - prettyprinter
    - regex-applicative
    - relude
    - say
    - tagsoup
    - template-haskell
    - text
    - th-orphans
    - timeit
    - transformers
    - uniplate
    - unordered-containers
    - vector
    - vector-sized
    - word-wrap
    - xeno
description: Please see README.md
