name: release-command
on:
  repository_dispatch:
    types: [release-command]

jobs:
  make-release:
    runs-on: ubuntu-20.04
    steps:
      - uses: cachix/install-nix-action@v8
      - uses: cachix/cachix-action@v6
        with:
          name: vulkan-haskell
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

      # Checkout the pull request branch
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.TUVOK_TOKEN }}
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
          ref: ${{ github.event.client_payload.pull_request.head.ref }}
          submodules: recursive

      - run: |
          echo "${GITHUB_REF##*/}"
          curl -H "Authorization: token ${{ secrets.TUVOK_TOKEN }}" https://api.github.com/user |
            jq --raw-output '[.id,.login] | @tsv' | read id login
          git config user.name "$login"
          git config user.email "$id+$login@users.noreply.github.com"
          git remote -v

      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.TUVOK_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: rocket

      - run: |
          nix-shell --arg forShell false --arg hoogle false -A vulkan.env --run \
            "./release.sh --vulkan ${{ github.event.client_payload.slash_command.args.named.vulkan }}"
          git push origin HEAD:${{ github.event.client_payload.pull_request.head.ref }}

