name: Tag Latest Release

on:
  push:
    branches:
    - master

jobs:
  update:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Fetch everything
        token: ${{ secrets.PAT }}
    - uses: expipiplus1/action-automation/tag-latest-release@HEAD
      with:
        token: ${{ secrets.PAT }}
        tagsAndFiles: |
          v package.yaml
          vma-v VulkanMemoryAllocator/package.yaml
          utils-v utils/package.yaml
